const products = [
  {
    id: 1,
    name: "Green Japanese tea - 100g",
    price: 12.99,
    picture: "product1-picture.jpg",
    comment:
      "Your natural and healthy Japanese tea to help you in your search for well-being",
    conservationAsset: "Long conservation",
    conservation: "Aluminium box for conservation",
    otherAsset: "Hand-harvested",
    otherAssetProperty: "100% hand-harvested Japanese tea",
    dimensions: "10cm x 6cm x 6cm",
    weight: "100g",
  },
  {
    id: 2,
    name: "Red Japanese tea - 100g",
    price: 13.99,
    picture: "product2-picture.jpg",
    comment:
      "Your natural and healthy Japanese tea to help you in your search for well-being",
    conservationAsset: "Long conservation",
    conservation: "Aluminium box for conservation",
    otherAsset: "Hand-harvested",
    otherAssetProperty: "100% hand-harvested Japanese tea",
    dimensions: "10cm x 6cm x 6cm",
    weight: "100g",
  },
  {
    id: 3,
    name: "Black Japanese tea - 100g",
    price: 13.99,
    picture: "product3-picture.jpg",
    comment:
      "Your natural and healthy Japanese tea to help you in your search for well-being",
    conservationAsset: "Long conservation",
    conservation: "Aluminium box for conservation",
    otherAsset: "Hand-harvested",
    otherAssetProperty: "100% hand-harvested Japanese tea",
    dimensions: "10cm x 6cm x 6cm",
    weight: "100g",
  },
  {
    id: 4,
    name: "Green Japanese tea refill - 100g",
    price: 9.99,
    picture: "product4-picture.jpg",
    comment:
      "Your natural and healthy Japanese tea to help you in your search for well-being",
    conservationAsset: "Eco-friendly",
    conservation: "Paper bag for low environmental impact",
    otherAsset: "Hand-harvested",
    otherAssetProperty: "100% hand-harvested Japanese tea",
    dimensions: "13cm x 10cm x 4cm",
    weight: "100g",
  },
  {
    id: 5,
    name: "Red Japanese tea refill - 100g",
    price: 10.99,
    picture: "product5-picture.jpg",
    comment:
      "Your natural and healthy Japanese tea to help you in your search for well-being",
    conservationAsset: "Eco-friendly",
    conservation: "Paper bag for low environmental impact",
    otherAsset: "Hand-harvested",
    otherAssetProperty: "100% hand-harvested Japanese tea",
    dimensions: "13cm x 10cm x 4cm",
    weight: "100g",
  },
  {
    id: 6,
    name: "Black Japanese tea refill - 100g",
    price: 10.99,
    picture: "product6-picture.jpg",
    comment:
      "Your natural and healthy Japanese tea to help you in your search for well-being",
    conservationAsset: "Eco-friendly",
    conservation: "Paper bag for low environmental impact",
    otherAsset: "Hand-harvested",
    otherAssetProperty: "100% hand-harvested Japanese tea",
    dimensions: "13cm x 10cm x 4cm",
    weight: "100g",
  },
  {
    id: 7,
    name: "Authentic Japanese tea pot",
    price: 109.99,
    picture: "product7-picture.jpg",
    comment:
      "Authentic handmade tea pot manufactured in Japan. Capacity: 400 ml",
    conservationAsset: "Genuine",
    conservation: "Made of fired volcanic clay of very high quality",
    otherAsset: "Taste of Japan",
    otherAssetProperty: "Tea pot with long diffusion",
    dimensions: "18cm x 20cm x 20cm",
    weight: "600g",
  },
  {
    id: 8,
    name: "Modern tea set",
    price: 29.99,
    picture: "product8-picture.jpg",
    comment:
      "Tea set composed of one tea pot in clay and wood (capacity 450ml) and two tea cups (180ml each)",
    conservationAsset: "Durable",
    conservation: "Manufactured in Italy, 30 years warranty",
    otherAsset: "Ergonomic",
    otherAssetProperty: "The handle allows an easy gripping",
    dimensions: "25cm x 20cm x 20cm",
    weight: "800g",
  },
  {
    id: 9,
    name: "Classic tea pot",
    price: 16.99,
    picture: "product9-picture.jpg",
    comment: "Tea pot made in the pure English Tradition (capacity 400ml)",
    conservationAsset: "Durable",
    conservation: "Manufactured in Great-Britain, 25 years warranty",
    otherAsset: "Flavour preserved",
    otherAssetProperty: "Shape studied to preserve tea flavor",
    dimensions: "25cm x 20cm x 20cm",
    weight: "500g",
  },
  {
    id: 10,
    name: "Ecofriendly flask",
    price: 19.99,
    picture: "product10-picture.jpg",
    comment: "Ecologic and modern flask to bring everywhere (capacity 750ml)",
    conservationAsset: "Eco-friendly",
    conservation: "Made of 100% recycled materials",
    otherAsset: "Non-slip bottom",
    otherAssetProperty: "Bottom made of a patented ecologic rubber",
    dimensions: "13cm x 4cm",
    weight: "100g",
  },
];

export default products;
